# Generated by Django 4.1.7 on 2023-04-15 08:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('connectionStatus', models.CharField(default='', max_length=20)),
                ('InscriptionDate', models.DateField(default=datetime.date(2023, 1, 1))),
                ('firstName', models.CharField(default='', max_length=50)),
                ('lastName', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(default='+21600000000', max_length=20)),
                ('birthdate', models.DateField(default=datetime.date(1995, 11, 11))),
            ],
            options={
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='CommandDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commandNumber', models.PositiveIntegerField(default=0)),
                ('productNumber', models.PositiveIntegerField(default=0)),
                ('productName', models.CharField(default='', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unitPrice', models.FloatField(default=0.0)),
                ('totalPrice', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendingNumber', models.PositiveIntegerField(default=1)),
                ('Type', models.CharField(default='', max_length=20)),
                ('Price', models.FloatField(default=0.0)),
                ('destination', models.TextField(default='Rue, la ville , code de postal')),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panierNumber', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=20)),
                ('price', models.FloatField(default=0)),
                ('stock', models.PositiveSmallIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/product_image')),
                ('description', models.TextField(blank=True, null=True)),
                ('expirationDate', models.DateField(default=datetime.date(2023, 12, 31))),
                ('fabricationDate', models.DateField(default=datetime.datetime(2023, 4, 15, 8, 8, 37, 932852, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_cmd', models.DateField(default=datetime.datetime(2023, 4, 15, 8, 8, 37, 938670, tzinfo=datetime.timezone.utc))),
                ('quality', models.PositiveSmallIntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunipharmaApp.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunipharmaApp.product')),
            ],
            options={
                'verbose_name': 'Command table',
                'db_table': 'command',
                'ordering': ['-date_cmd'],
                'unique_together': {('client', 'product', 'date_cmd')},
            },
        ),
        migrations.AddField(
            model_name='client',
            name='clientProduct',
            field=models.ManyToManyField(through='tunipharmaApp.Command', to='tunipharmaApp.product'),
        ),
    ]
