# Generated by Django 4.1.7 on 2023-04-15 16:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunipharmaApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='clientProduct',
        ),
        migrations.DeleteModel(
            name='Panier',
        ),
        migrations.AlterUniqueTogether(
            name='command',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='command',
            name='clientNumber',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='command',
            name='commandNumber',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='command',
            name='status',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='commanddetails',
            name='commad',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tunipharmaApp.command'),
        ),
        migrations.AddField(
            model_name='deliveryinformation',
            name='commad',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tunipharmaApp.command'),
        ),
        migrations.AlterField(
            model_name='command',
            name='date_cmd',
            field=models.DateField(default=datetime.datetime(2023, 4, 15, 16, 42, 10, 424106, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='command',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tunipharmaApp.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fabricationDate',
            field=models.DateField(default=datetime.datetime(2023, 4, 15, 16, 42, 10, 423107, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterModelTable(
            name='commanddetails',
            table='command details',
        ),
        migrations.AlterModelTable(
            name='deliveryinformation',
            table='delivery information',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.RemoveField(
            model_name='command',
            name='client',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
