# Generated by Django 4.1.7 on 2023-04-24 12:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tunipharmaApp', '0005_remove_product_image_alter_command_date_cmd_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='expirationDate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fabricationDate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/product_image'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='command',
            name='date_cmd',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(default='', max_length=20)),
                ('categoryDescription', models.CharField(default='', max_length=100)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tunipharmaApp.product')),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
